<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>b6f02b97-89e7-40e1-af27-bcca6b6ac74a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="NLog.Database" Version="6.0.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Urbancode.Accounts.API.Application\Urbancode.Accounts.API.Application.csproj" />
      <ProjectReference Include="..\Urbancode.Accounts.API.Infrastructure\Urbancode.Accounts.API.Infrastructure.csproj" />
    </ItemGroup>

</Project>
