<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>bdb3b490-989a-43c3-a0e6-023f8f000cd2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.72" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Npgsql">
        <HintPath>..\..\..\.nuget\packages\npgsql\10.0.1\lib\net8.0\Npgsql.dll</HintPath>
      </Reference>
      <Reference Include="System.Data.SqlClient">
        <HintPath>..\..\..\.nuget\packages\system.data.sqlclient\4.9.0\lib\net8.0\System.Data.SqlClient.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Urbancode.Accounts.API.Application\Urbancode.Accounts.API.Application.csproj" />
      <ProjectReference Include="..\Urbancode.Accounts.API.Domain\Urbancode.Accounts.API.Domain.csproj" />
    </ItemGroup>

</Project>
